tajo/ladle

- packages/ladle/lib/app/src/sidebar/tree-view.tsx
Currently, command/control click on sidebar links (to open page in a new tab) is broken due to how the default click event behavior is disabled. This makes for a good same-tab experience so that users don't get a page-load flash and can load quickly. This change checks for if the meta/ctrl keys are pressed and will fallback to browser controls
> allow meta/ctrl click on sidebar links

- README.md
It's too slow in South Korea.
I think it's maybe a problem with the camo proxy...
So I changed it to raw.githubusercontent.com url.
How think about this image url?
> Change ladle-baseweb image url of README.md

- packages/ladle/lib/cli/vite-base.js
- packages/ladle/lib/shared/default-config.js
- packages/ladle/lib/shared/types.ts
- packages/website/docs/config.md
Hi! 👋🏽 
I found this package today and started to evaluate it as a replacement for Storybook.
During my first look at it, I didn't find a way to serve files statically like the `-s, --static-dir` in Storybook.
`vite` has the [`publicDir` config option]((https://vitejs.dev/config/#publicdir)), currently not supported.
It defaults to `public` but it can be `false` to disable the behaviour.
The `root` directory for `ladle` is inside the `node_modules` folder.
Therefore, I used the `process.cwd()` to figure the absolute path.
With this, users can use only `publicDir: 'myFolder'` as in `vite` itself.
❗ I'll work on a documentation update tomorrow but decided to open the PR for feedback.
If you have any opinions or suggestions about this change, let me know below.
> feat: support publicDir from vite

- packages/ladle/lib/cli/vite-plugin/generate/get-components-import.js
- packages/website/docs/providers.md
Adds support for `components.ts` and `components.jsx`, making it far easier to e.g. use JavaScript React.
Reduces I/O operations - especially if multiple `components.{js,jsx,ts,tsx}` are found.
> feat: add support for components.ts and components.jsx in getComponents util

- packages/ladle/lib/app/src/no-stories.tsx
> fix: misspelled docs link

- .changeset/twelve-turtles-fold.md
- packages/ladle/lib/cli/vite-base.js
- packages/ladle/lib/shared/default-config.js
- packages/ladle/lib/shared/types.ts
- packages/website/docs/config.md
Why:
Setup react-native-web requires vite resolve.extensions to be set to for example:
```javascript
resolve: {
extensions:['.web.tsx', '.web.ts', '.mjs', '.js', '.ts', '.jsx', '.tsx', '.json']
},
```
This is just another case of limited config options for vite.
https://necolas.github.io/react-native-web/docs/multi-platform
The file for react web components will simply have highest priority for `.web.ts?x` extension.
> feat: allow configuration Vite config.resolve object

- .changeset/green-emus-prove.md
- packages/ladle/lib/cli/vite-plugin/vite-plugin.js
- turbo.json
fixes https://github.com/tajo/ladle/issues/132 (somewhat)
This is a workaround. It seems that `react-refresh` is not able to detect components defined through `.bind({})` (used for story controls). An upstream fix might be possible there. 
This PR detects `.bind({})`, opts-out of the HMR for top-level stories and forces full page reload. It's not as good experience as react refresh but at least it preserves controls state since we persist it through the URL.
As a user, you can also avoid this by moving the component (template) code into a separate file. Or if you use controls for a single story, you don't need template/bind pattern at all.
> Force page reload when stories are defined through .bind({})

- .changeset/giant-shirts-remain.md
- e2e/config-ts/.ladle/config.mjs
- e2e/config-ts/CHANGELOG.md
- e2e/config-ts/ladle-vite.config.js
- e2e/config-ts/package.json
- e2e/config-ts/src/hello.show.tsx
- e2e/config-ts/tests/hello.spec.ts
- e2e/config-ts/vite-my-plugin.ts
- e2e/config-ts/vite.config.ts
- package.json
- packages/ladle/lib/cli/get-user-vite-config.js
- pnpm-lock.yaml
- pnpm-workspace.yaml
Hi maintainers 👋 
I would like to contribute to the great project!
I tried to follow [the Contributing Guide](https://github.com/tajo/ladle/blob/42e3cf9a0d6273a9850850f5e6836871316ef63d/CONTRIBUTING.md).
(Only for the package maintainers) a new E2E packages is added.
Ladle was not able to handle `vite.config.ts` the way Vite does.
For example, Ladle was not able to load `vite.config.ts` which imported other TS modules.
(Only for the package maintainers) recognize a new e2e workspace with `pnpm install`.
> Load vite.config.ts the same way as Vite

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/seccomp_profile.json
- .gitignore
- CONTRIBUTING.md
Provide the ability to work on this project inside of a Docker container and/or on GitHub Codespaces through the creation of `devcontainer` and `Docker` configuration files.
This helps contributors to all share the same development environment, notably, ensuring that everyone uses the same versions of the various tools required for development of Ladle. Further, it makes it possible to work on the project without the need to install this project's tools and dependencies globally on your computer.
The configurations build upon the official `Playwright` Docker images (and security profiles) to ensure contributors have everything they need to run development, testing, linting, and building processes.
> feat(devcontainer): add devcontainer config files

- .changeset/old-pumas-rush.md
- packages/ladle/lib/cli/vite-dev.js
- packages/ladle/lib/cli/vite-plugin/parse/get-entry-data.js
Improve the performance of virtual stories modules. `fs.promises.readFile` is much slower than `fs.promises.readSync` and blocking CPU doesn't matter in our use case anyway. Also don't run the story watcher on the startup.
> Improve startup performance, related to the virtual story module

- .changeset/funny-cats-drive.md
- e2e/config/ladle-vite.config.js
- packages/ladle/lib/cli/vite-base.js
Automatically detect the user config format for `resolve.alias` before configuring ladle for react v17.
Fixes #184
> Fix `resolve.alias` compat issue

- packages/ladle/lib/app/src/compose-enhancers.tsx
Hi, Ladle team,
I recently tried this tool as an alternative to Storybook. 
When I started the server, It didn't show any content on the screen, then I checked the console log info 
and found this error message:
After that, I tried to change the code on that file and then tested it locally, the error has disappeared expectly and I can see this tool works well now. 
I think my change is pretty straightforward, hope you can approve. 
Thanks
> Fix: React is not defined on `compose-enhancers.tsx`

- .changeset/purple-gorillas-do.md
- packages/ladle/lib/cli/apply-cli-config.js
- packages/ladle/lib/cli/build.js
- packages/ladle/lib/cli/cli.js
- packages/ladle/lib/cli/preview.js
- packages/ladle/lib/cli/serve.js
- packages/ladle/lib/cli/vite-base.js
- packages/ladle/lib/cli/vite-dev.js
- packages/ladle/lib/cli/vite-preview.js
- packages/ladle/lib/cli/vite-prod.js
- packages/ladle/lib/shared/default-config.js
- packages/ladle/lib/shared/types.ts
- packages/website/docs/cli.md
- packages/website/docs/config.md
fixes https://github.com/tajo/ladle/issues/201
This allows doing `ladle build --base=/my-project/`, for e.g. building Ladle storybooks to GitHub Pages.
I also took the opportunity to clean up some CLI parsing code that was unnecessarily triplicated.
> Add --base and --mode options

- .changeset/polite-gorillas-jump.md
- packages/ladle/lib/cli/vite-dev.js
Fixes: #227 
if I set `base` option in `vitest.config.ts` as `"./"`, ladle dev server causes redirect loop with `base: ./` config. I fixed this issue by preventing redirect if `base` option in `vite.config.ts` is `"./"` same as `"/"`
> Fix(dev-server): prevent redirect loop in top page

- .changeset/wise-cheetahs-suffer.md
- e2e/config/.ladle/config.mjs
- e2e/config/src/specific-file.custom.tsx
- e2e/config/tests/custom-path.spec.ts
- packages/example/.ladle/config.mjs
- packages/ladle/lib/cli/build.js
- packages/ladle/lib/cli/vite-dev.js
- packages/ladle/lib/cli/vite-plugin/vite-plugin.js
- packages/website/docs/config.md
Current issue:
The current version files to compile and thrown as error as describe in
https://github.com/tajo/ladle/issues/208
fix:
config file now supports array of strings as below
```
stories: [
"src/a11y.stories.tsx",
"src/control.stories.tsx",
"src/controls.stories.tsx",
],
```
resolves: #208
> fix(config-file-entry): support config entry stories in array of strings

- .changeset/tame-falcons-learn.md
- .github/workflows/release.yml
- packages/ladle/package.json
- packages/ladle/publish-next.js
- packages/ladle/scripts/package-types-helpers.js
- packages/ladle/scripts/revert-package-types.js
- packages/ladle/scripts/update-package-types.js
- packages/ladle/tsconfig.typesoutput.json
- release.sh
In order to get TS types working correctly for "Node16" and "NodeNext"
Closes #267 
For normal npm versions: 
1. Update `release.sh` to run `update-package-types.js`, which 
2. Makes a copy of package.json as `backup-package.json`, and then 
3. Writes the necessary changes out to `package.json`, and then
4. Generates the types with an npm script, and then
5. Reverts `package.json` from `backup-package.json` and deletes the backup-package.json.
😓 
For `next` npm versions, it was a bit easier since there was already a NodeJS script modifying package.json, so I just hooked into it to make those changes and made sure the npm script was executed.
---
I'm very open to changing any and all of this if you think there's something that needs to be changed. 👍
> Add scripts that modify the package.json before publishing

- .changeset/cyan-flies-yell.md
- packages/ladle/package.json
- packages/ladle/scripts/package-types-helpers.js
Followup to #267 and #275 
Tested both ESM and CJS projects (by modifying the `example` package) and this works.
> Fix types for CJS projects using TypeScript NodeNext/Node16

- .changeset/dull-stingrays-explain.md
- .gitignore
- packages/ladle/package.json
- packages/ladle/scripts/package-types-helpers.js
- packages/ladle/tsconfig.typesoutput.json
By emitting the types to their own folder, and then `exclude`-ing that folder in the `tsconfig.typesoutput.json`, it doesn't bother TS anymore that you have emitted twice.
Named the folder `typings-for-build` (and that folder should only show up when publishing, or testing the publish) but feel free to suggest changes for that name. 🙂 
Tested in the `example` repo for "NodeNext + CJS" and "NodeNext + ESM" and no issues.
> Fix issue when publishing both next and current release

- .changeset/clean-weeks-beam.md
- packages/ladle/package.json
Fix for issue found, as noted https://github.com/tajo/ladle/issues/280#issuecomment-1281141946
> Include the typings folder when publishing

- .changeset/famous-ducks-cheer.md
- packages/example/src/controls.stories.tsx
- packages/ladle/lib/app/src/addons/control.tsx
Employs minimal changes to the existing code base. In addition I added undefined values to the example application for the radio and select options.
> Solves consoles errors when using undefined options in argTypes, and displays 'undefined' as an option in control addon (select and radio)

- packages/website/docs/addons.md
Currently leads back to `Stories`
> [website] Fix link to Controls page from Addons page

- .changeset/witty-eagles-peel.md
- e2e/addons/src/controls.stories.tsx
- e2e/addons/tests/controls.spec.ts
- packages/example/src/controls.stories.tsx
- packages/ladle/lib/app/src/addons/control.tsx
- packages/ladle/lib/app/src/args-provider.tsx
fixes #320,#318
The initial implementation was trying to be more strict/smart. This reverts to `undefined` as the default for all controls so it works the same way as Storybook's implementation.
> Use undefined as default for controls

- .changeset/hip-roses-yawn.md
- packages/ladle/lib/cli/vite-dev.js
This is a security issue when local developing on shared network.
The dev server also doens't autobind to all network interfaces (aligned with the Vite's default).
> Preventing Vite to serve files outside of root workspace.

- .changeset/late-mirrors-pull.md
- e2e/addons/package.json
- e2e/addons/playwright.config.ts
- e2e/addons/src/controls.stories.tsx
- e2e/addons/tests/controls.spec.ts
- packages/example/src/controls.stories.tsx
- packages/ladle/lib/app/ladle.css
- packages/ladle/lib/app/src/addons/control.tsx
- packages/ladle/lib/app/src/args-provider.tsx
- packages/ladle/lib/shared/types.ts
- packages/website/docs/controls.md
- pnpm-lock.yaml
Adds a new range type control which should be Storybook compatible.
Tests, updated docs, and changelog included. Hopefully, I didn't forget anything, if so let me know.
> feat: range control

- .changeset/five-avocados-bow.md
- packages/ladle/lib/app/exports.ts
- tsconfig.json
- type-tests/argTypes.test.tsx
- type-tests/args.test.tsx
- type-tests/meta.test.tsx
Uses `P` passed to `Story<>` to enhance `Args` and `ArgTypes` so that `args` can only contain key/value pairs defined in `P`, and `argTypes` can only contain keys defined in `P`.
Improves `ArgType` type to include checks for `control` that now checks for `type` and `options` validity, and for `defaultValue`.
Adds very basic `Meta` type.
Adds `type-tests` which are files that are built to deliberately trigger type errors - then marks them with `@ts-expect-error` so that:
* Any unmarked type error triggers an error
* Any marked type error which is NOT triggered triggers an error
Before:
After:
`argTypes`:
> Improved type safety in `args`, `argTypes` and `meta` in Stories

- .changeset/ninety-penguins-jog.md
- e2e/programmatic/.ladle/config.mjs
- e2e/programmatic/build.js
- e2e/programmatic/serve.js
- packages/ladle/lib/app/src/app.tsx
- packages/ladle/lib/app/src/get-config.ts
- packages/ladle/lib/app/src/no-stories.tsx
- packages/ladle/lib/cli/apply-cli-config.js
- packages/ladle/lib/cli/vite-plugin/generate/get-config-import.js
- packages/ladle/lib/cli/vite-plugin/generate/get-generated-list.js
- packages/ladle/lib/cli/vite-plugin/vite-plugin.js
- packages/ladle/tests/get-generated-list.test.ts
- packages/website/docs/config.md
- packages/website/docs/programmatic.md
Change the way how values from config.mjs are passed to the client. We were doing direct import into the app but that breaks cases when config.mjs uses Node APIs. Also, it risks leaking potentially sensitive stuff from the CLI side. And it's cubersome when used through programatic API / wrapper libraries. The new solution picks just a subset of config.mjs values that are really needed in the client, serializes them and embeds them into our virtual module.
> Pass config.mjs values into the client through serialization and virtual module

- .changeset/ten-buses-think.md
- packages/ladle/lib/cli/vite-preview.js
The `base` cli configuration option is ignored for the preview mode using `ladle preview`. 
As pointed out in the [documentation](https://ladle.dev/docs/cli#preview-command), `--base` should be supported and initially read from the configuration folder (default `.ladle`).
So if you specify a base path, the preview just opens at the desired URL (for example *http://localhost:8080*) and then you'll get the notification:
> Cannot GET /
In my case, I have to append **/styleguide** each time manually and it looks broken on initial browser open.
```typescript
// .ladle/config.mjs
export default {
…
base: '/styleguide/',
};
```
Adding `config.base` to the `serverUrl` solves the issue.
> Add `--base` cli option in preview mode

- .changeset/fifty-stingrays-drum.md
- e2e/addons/src/controls.stories.tsx
- packages/ladle/lib/app/src/addons/control.tsx
When a range type argument is stored in the url and the page is reloaded, the value is a string instead of number until the range is adjusted.
> Fix range value initially being a string when loading from url search params

- .changeset/dirty-dots-fly.md
- packages/ladle/lib/cli/open-browser.js
- packages/ladle/lib/cli/vite-dev.js
- packages/ladle/lib/cli/vite-preview.js
- packages/ladle/package.json
- pnpm-lock.yaml
Using the create-react-app open browser logic that works best across the devices and setups like VSCode remote (with an addition of Yarn PnP support). Removing the `default-browser` dep and its logic, it was sketchy - asking for sudo.
This also just matches Vite's [server.open](https://vitejs.dev/config/server-options.html#server-open). You can use ENV variables to adjust the browser that should be open.
> Use create-react-app openBrowser script. 

- .changeset/silly-flies-complain.md
- packages/ladle/lib/cli/apply-cli-config.js
- packages/ladle/lib/cli/cli.js
- packages/ladle/lib/cli/vite-dev.js
- packages/ladle/lib/cli/vite-preview.js
- packages/ladle/lib/shared/types.ts
- packages/website/docs/cli.md
- packages/website/docs/config.md
This PR adds a `--host [string]` command line option to the serve and preview commands that maps to Vite's `--host / host:` configuration parameter.
Today, the host can be configured in `vite.config.ts`, but cannot be configured per-execution. Adding a `--host` command line option allows the host to be configured per-execution.
This parameter is useful to me when running playwright visual tests in a docker container.
When listening on 127.0.0.1 on the host (the default), the docker container cannot access Ladle. To let the container access Ladle, either Ladle must listen on an address in `docker0` or on `0.0.0.0`. There are problems with both:
- If Ladle is configured to listen on `docker0`, then it fails to bind when the `docker0` interface is unavailable, which occurs when docker is …
> Add a --host option for serve and preview

- packages/website/docs/nextjs.md
Same as `next/image`, `next/link` needs to be replaced by a simple `<a {...props} />` tag.
It is probably the same for a lot of other next-specific components.
> docs: add nextjs clarifications

- .changeset/yellow-oranges-tan.md
- packages/ladle/lib/app/src/no-stories.tsx
- packages/ladle/lib/app/src/story-not-found.tsx
- packages/ladle/lib/app/src/story.tsx
NoStories component served two purposes, and these purposes had little in common. Furthermore, it was not fully type safe as all props were optional. Splitting these components make them easier to work with.
I added Back to home link so that if you are in full screen mode without navigation you still have an easy escape hatch.
I fixed GitHub name which had a typo in it.
> Split NoStories and StoryNotFound components, improve wording, add Back to home link, fix typo in GitHub name

- e2e/config-ts/src/paths.show.tsx
- e2e/config-ts/src/to/label.ts
- e2e/config-ts/tests/paths.spec.ts
- e2e/config-ts/tsconfig.json
- packages/ladle/package.json
- pnpm-lock.yaml
- tsconfig.json
fixes #417
version 4+ causing issue in https://github.com/janakg/tsconfig-path-lib-path-issue
added a test into our monorepo, strangely works for 3.6 and 4.1+ but not for 4.0
pinning it down to 3.6.0 since that works in both setups
> Pin vite-tsconfig-path to 3.6

- .changeset/tame-tools-jam.md
- packages/ladle/package.json
- pnpm-lock.yaml
- Bumps Ladle's Vite version to the latest v4.3.9 to fix the recent advisory posted [here](https://github.com/advisories/GHSA-353f-5xf4-qw67).
Here is the Vite [changelog](https://github.com/vitejs/vite/blob/v4.3.9/packages/vite/CHANGELOG.md#439-2023-05-26) for this version.  Also please let me know if `minor` is not correct for this change
> Use Vite v4.3.9

- packages/website/docs/nextjs.md
Hello there! 👋🏻
As discussed on Discord, it took me a while to make Ladle and Next.js work together due to my use of frontend environment variables.
I have included a brief explanation and code snippet in the existing Next.js documentation. Please let me know if anything is unclear or if there's anything missing. 😇
Here is my original message from Discord:
> Hello there! 👋🏻 I encountered some difficulties while trying to make Ladle and Next.js work together. At first, I realized that I needed to inform Ladle to include the .env.local file. Fortunately, I came across this helpful resource: [Ladle Documentation](https://ladle.dev/docs/nextjs). However, it didn't provide any information about environment variables. After some time, I discovered that I needed to utilize the Vite config to …
> Add nextjs env file handling to docs

- .changeset/eight-cobras-add.md
- packages/ladle/lib/app/exports.ts
This allows extending the interface to define custom meta types within your own implementation.
```ts
declare module "@ladle/react" {
export interface Meta {
myCustomMeta: string;
}
}
```
> Changes Meta from a type to an interface

- e2e/baseweb/.ladle/components.tsx
- e2e/baseweb/package.json
- e2e/baseweb/playwright.config.ts
- e2e/baseweb/src/hello.stories.tsx
- e2e/baseweb/tests/hello.spec.ts
- e2e/baseweb/vite.config.js
- package.json
- packages/ladle/lib/app/src/story.tsx
- packages/ladle/lib/app/src/synchronize-head.tsx
- pnpm-lock.yaml
- pnpm-workspace.yaml
> Improve support for CSS in JS libs, add tests for BaseWeb

- packages/website/docs/width.mdx
I had to dig in to the code to find out why the `defaultValue` didn't work. Maybe the name of the variable has changed and docs not updated.
> Fix docs on default width

- .changeset/cuddly-students-destroy.md
- packages/ladle/lib/app/src/icons.tsx
Previously, the first svg in the ternary operation was the chevron pointing down. When "rotate" is true, we should return the chevron pointing right instead.
Fixes #502 
* https://github.com/tajo/ladle/issues/502
* https://github.com/tajo/ladle/pull/495
> Switch rotated chevron icon

- CONTRIBUTING.md
I added some notes to the documentation about the debugging methods for E2E testing, as I was a little lost on how to contribute to it.
About `> **NOTE**` notation: https://github.com/orgs/community/discussions/16925
Thank you.
> add e2e test tips to docs

- .changeset/itchy-peas-repeat.md
- packages/ladle/lib/cli/cli.js
- packages/ladle/lib/cli/vite-dev.js
- packages/ladle/lib/shared/default-config.js
- packages/ladle/lib/shared/types.ts
- packages/website/docs/cli.md
- packages/website/docs/config.md
When running in a multi tenant environment, we're seeing instances where chokidar exceeds the available `max_user_watches`, with the error message `System limit for number of file watchers reached, watch 'src'`. While we could increase that limit, there is no reason to watch the file system in this scenario. Making this change within ladle, rather than customizing through `vite.config.js` is important because ladle starts its own chokidar watch outside of vite.
This PR adds a `--noWatch` option to the serve command to disable chokidar file system watching. It currently does this by adding all files to the [`ignored` watcher options](https://vitejs.dev/config/server-options.html#server-watch). A [recent PR](https://github.com/vitejs/vite/pull/14208) to vite added `null` as an acceptable …
> Add --noWatch option to serve command

- packages/website/blog/2023-09-19-ladle-v3.md
- packages/website/docs/decorators.md
- Fixed the spelling of the word, "below"
- Added commas in an attempt to make a sentence easier for people to read
> Fix typos in documentation

- .changeset/witty-lizards-jog.md
- packages/ladle/lib/cli/vite-dev.js
- packages/ladle/lib/shared/default-config.js
- packages/ladle/lib/shared/types.ts
- packages/website/docs/config.md
Fixes https://github.com/tajo/ladle/issues/557
> Add hmrHost and hmrPort to the ladle config

- packages/website/docs/nextjs.md
Hi, thanks for your work on Ladle! It's a really nice tool!
The path to AppRouterContext was moved a few months back. This small patch updates the documentation with the new import path.
See https://github.com/vercel/next.js/commit/a5b7c77c1ff0096af7609a8bfc1e064d30db4e30#diff-421107ce62efb02560358d25c5eb086d5d82d2ad1c7c4929ebfb768c2ea1c973 for upstream next.js changes
> Update documentation Next.js runtime library import path

- .github/workflows/ci.yml
It looks like #564 missed updating the pnpm/action-setup version in the ci.yml workflow, so CI is failing on a couple of PRs I opened a few days ago.
> Updates pnpm/action-setup to v4 in ci workflow

- .changeset/dirty-zoos-jam.md
- packages/ladle/lib/app/exports.ts
- packages/ladle/lib/cli/vite-plugin/generate/get-meta-json.js
- packages/ladle/lib/shared/types.ts
I'm using [visual snapshots](https://ladle.dev/blog/visual-snapshots/) in my project, and our TypeScript rules in the project dictate that I needed to define the type for the shape of the meta.json file.
I figured it might be a good idea to formally define these types in the project and export them for consumers of the library in case the shape changes in the future.
> Adds MetaJson types

- .changeset/witty-terms-end.md
- packages/ladle/lib/app/src/app.tsx
- packages/ladle/lib/app/src/sidebar/main.tsx
- packages/ladle/lib/app/src/sidebar/tree-view.tsx
This pull request addresses issue #555.
Changes Made:
- Fixed the query preservation when toggling the full-page preview.
- Improved type definitions for searchRef and firstChild.
Omitted the implementation of restoring scroll position, as I believe it should be handled as a separate task.
> Preserve query on toggling full page preview

- packages/website/docs/nextjs.md
When working with nextjs, image component has "fill" property. If not handled correctly, components in Ladle look different than on the page.
> Improve UnoptimizedImage docs

- .changeset/gold-students-doubt.md
- e2e/config/.ladle/config.mjs
- e2e/config/tests/expand-story-tree.spec.ts
- e2e/config/tests/hello.spec.ts
- packages/example/.ladle/config.mjs
- packages/ladle/lib/app/src/sidebar/main.tsx
- packages/ladle/lib/app/src/sidebar/tree-view.tsx
- packages/ladle/lib/cli/vite-plugin/generate/get-config-import.js
- packages/ladle/lib/shared/default-config.js
- packages/ladle/lib/shared/types.ts
- packages/website/docs/config.md
Feature: add `expandStoryTree` config flag to expand all stories
Relates to https://github.com/tajo/ladle/issues/423, I saw a follow up comment but no movement, so decided to follow up on the changes in case this is still relevant.
> FEAT: add expandStoryTree config flag

- README.md
> Note on powershell in quick start

- .changeset/grumpy-seas-drum.md
- e2e/addons/tests/docs.spec.ts
- packages/ladle/lib/app/src/addons/source.tsx
This PR fixes Issue #561, which was quite annoying for us when using ladle in dev mode.
I added a playwright test and ensured that it actually fails without my change.
The change was made according to the prism react renderer documentation (https://www.npmjs.com/package/prism-react-renderer#usage), where there is no key in the getTokenProps function. It seems like this prop is just forwarded.
> Fix mdx code blocks throwing errors in dev console

- .changeset/tame-crews-sing.md
- packages/example/src/controls.stories.tsx
- packages/ladle/lib/app/src/args-provider.tsx
Added explicit validation for `undefined`, so falsy values (`0`, `false`, `''`, etc.) are not replaced by a default value
See #612
> fix: use defaultValue only if value is undefined
